on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github --target-version=py310 .

  test:
    name: Test with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements-dev.txt coverage
      - name: Test with pytest
        run: coverage run -m pytest -v -s
      - name: Generate Coverage Report
        run: coverage report -m
